#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

\rm -rf 0
# \rm -r constant/extendedFeatureEdgeMesh/
\rm -f constant/triSurface/*.eMesh*
\rm -f *.obj
\rm -f *.log
\cp -r 0.org 0
echo "0 directory is refleshed"

